(()=>{'use strict';
const $=id=>document.getElementById(id),key='ukiwa-denken-study-v2',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let catalog=[],answers={},explanations={},solutionPages={},questions=[],state={records:{},last:null},queue=[],pos=0,shown=false,renderId=0;const packs=new Map();
try{const s=JSON.parse(localStorage.getItem(key));if(s?.records&&typeof s.records==='object')state=s}catch{}
function stats(){const r=questions.map(q=>state.records[q.id]||{});$('stats').textContent=`収録 ${questions.length}問 ／ 学習済み ${r.filter(x=>x.attempts).length}問 ／ 要復習 ${r.filter(x=>x.retry).length}問`;$('start').disabled=!questions.length;$('resume').disabled=!questions.some(q=>q.id===state.last)}
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{$('storage-note').textContent='記録を保存できません。閉じると今回の記録は失われます。'}stats()}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error('教材を取得できません');return r.json()}
async function unpack(name){if(packs.has(name))return packs.get(name);const p=(async()=>{const r=await fetch('denken-assets/'+name+'.pack');if(!r.ok)throw Error('教材を取得できません');const b=Uint8Array.from(atob((await r.text()).trim()),c=>c.charCodeAt(0));return JSON.parse(await new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream('gzip'))).text())})();packs.set(name,p);try{return await p}catch(e){packs.delete(name);throw e}}
function filtered(){return questions.filter(q=>{const r=state.records[q.id]||{},m=$('mode').value;return(!$('stage').value||q.stage===$('stage').value)&&(!$('subject').value||q.subject===$('subject').value)&&(!$('year').value||String(q.year)===$('year').value)&&(m==='all'||m==='new'&&!r.attempts||m==='retry'&&r.retry||m==='saved'&&r.saved)})}
function record(ok){const q=queue[pos],r=state.records[q.id]||{};state.records[q.id]={...r,attempts:(r.attempts||0)+1,retry:!ok,lastCorrect:ok,draft:[],date:new Date().toISOString()};save()}
function pages(node,list,start,end){node.innerHTML=list.slice(start,end).map((s,i)=>`<div class="paper-page" role="img" aria-label="原本 ${start+i+1} ページ">${s}</div>`).join('')}
async function render(){const token=++renderId,q=queue[pos];shown=false;state.last=q.id;save();const r=state.records[q.id]||{},a=answers[q.year]?.[q.subject]?.[q.number];$('desk').innerHTML=`<p class="progress">${pos+1} / ${queue.length} 問</p><span class="badge">${q.year}年度 · ${esc(q.stage)} · ${esc(q.subject)} · 問${q.number}</span><label class="jump-label">問題へ移動<select id="jump"></select></label><div class="actions"><button id="bookmark" aria-pressed="${!!r.saved}">${r.saved?'★ 保存済み':'☆ あとで解く'}</button><a href="${esc(q.source)}" target="_blank" rel="noopener">原本PDF ↗</a></div><p class="source">出典：${esc(q.title)}（電気技術者試験センター）。原本のページを表示しています。</p><div class="exercise"><div><div class="paper-tools"><label>表示倍率<select id="zoom"><option>100%</option><option>125%</option><option>150%</option></select></label></div><div id="paper" class="paper">図と数式を読み込んでいます…</div></div><div class="answer-panel"><h2>${a?'解答を選ぶ':'解答を組み立てる'}</h2>${a?'<p class="small">原本の解答群から各空欄の記号を選択。</p><div id="slots"></div>':'<p class="small">記述式は公式解答と照合して理解度を記録します。</p>'}<label>考え方・途中式メモ<textarea id="memo" placeholder="使う公式、途中式、気づいたこと…"></textarea></label><button id="judge" class="primary">${a?'採点して答え合わせ':'公式解答を開く'}</button><div id="feedback"></div></div></div><div class="actions"><button id="prev" ${pos===0?'disabled':''}>← 前の問題</button><button id="next">${pos+1===queue.length?'学習結果を見る':'次の問題 →'}</button></div><div id="solution"></div>`;
queue.forEach((item,i)=>{const o=document.createElement('option');o.value=i;o.textContent=item.year+' '+item.subject+' 問'+item.number;o.selected=i===pos;$('jump').append(o)});$('jump').onchange=()=>{pos=Number($('jump').value);render()};
if(a)a.forEach((_,i)=>{const l=document.createElement('label');l.textContent='空欄 ('+(i+1)+')';const s=document.createElement('select');s.dataset.slot=i;s.setAttribute('aria-label','空欄 '+(i+1));s.innerHTML='<option value="">未選択</option>'+[...'イロハニホヘトチリヌルヲワカヨ'].map(x=>`<option>${x}</option>`).join('');s.value=r.draft?.[i]||'';s.onchange=()=>{state.records[q.id]={...(state.records[q.id]||{}),draft:[...document.querySelectorAll('[data-slot]')].map(x=>x.value)};save()};l.append(s);$('slots').append(l)});
$('memo').value=r.memo||'';$('memo').oninput=()=>{state.records[q.id]={...(state.records[q.id]||{}),memo:$('memo').value};save()};$('zoom').onchange=()=>{$('paper').style.setProperty('--zoom',$('zoom').value)};$('bookmark').onclick=()=>{const r=state.records[q.id]||{};r.saved=!r.saved;state.records[q.id]=r;save();$('bookmark').textContent=r.saved?'★ 保存済み':'☆ あとで解く';$('bookmark').setAttribute('aria-pressed',String(r.saved))};$('judge').onclick=()=>reveal(a);$('prev').onclick=()=>{pos--;render()};$('next').onclick=()=>{if(pos+1<queue.length){pos++;render()}else{++renderId;$('desk').innerHTML='<h2>ここまで、おつかれさまでした。</h2><p>間違えた問題は「間違えた・要復習」から繰り返せます。未回答は学習済みになりません。</p>';stats()}};
try{const d=await unpack(q.year);if(token===renderId)pages($('paper'),d[q.paper],q.page,q.end)}catch(e){if(token===renderId)$('paper').textContent=e.message}}
async function reveal(a){if(shown)return;const q=queue[pos],ss=[...document.querySelectorAll('[data-slot]')];if(a&&ss.some(s=>!s.value)){$('feedback').textContent='空欄5つを選択してください。';return}shown=true;$('judge').disabled=true;const ok=a?ss.every((s,i)=>s.value===a[i]):null;if(a){record(ok);ss.forEach(s=>s.disabled=true)}$('feedback').innerHTML=`<section class="feedback ${ok===false?'wrong':''}"><h2>${ok===null?'公式解答と照合':ok?'全問正解です':'間違えた空欄を確認しよう'}</h2>${a?`<ol>${a.map((v,i)=>`<li>(${i+1}) ${ss[i].value===v?'○':'×'} あなた：${ss[i].value} → 正答：<strong>${v}</strong></li>`).join('')}</ol><p class="small">一次の公式資料は正答表です。正答を解答群・途中式と照合し、下の解説リンクで考え方を確認してください。</p>`:'<p>下の公式解答で途中式・単位・論述の要点を照合してください。</p><div class="actions"><button id="understood">解けた</button><button id="retry">要復習</button></div>'}</section>`;
const explanation=explanations[q.year+'-'+q.subject+'-'+q.number];const linkBox=document.createElement('p');if(explanation){const link=document.createElement('a');link.href=explanation.url;link.target='_blank';link.rel='noopener';link.className='explanation-link';link.textContent='この問題の詳しい解説を読む（'+explanation.publisher+'・別タブ）↗';linkBox.append(link)}else linkBox.textContent='この問題の外部解説リンクは未登録です。公式解答で照合してください。';$('feedback').append(linkBox);
if(ok===null)for(const [id,v]of[['understood',true],['retry',false]])$(id).onclick=()=>{record(v);$('understood').disabled=true;$('retry').disabled=true;$(id).textContent+=' · 記録しました'};
const sol=catalog.find(p=>p.answer&&p.year===q.year&&p.stage===q.stage);if(!sol){$('solution').textContent='この年度の公式解答は未収録です。';return}const token=renderId;$('solution').innerHTML=`<h2>${q.stage==='一次'?'公式正答表':'公式解答・計算過程'}</h2><p class="small">${esc(sol.title)}。該当科目・問番号を照合してください。</p><a href="${esc(sol.source)}" target="_blank" rel="noopener">解答原本PDF ↗</a><div id="solution-pages" class="paper">読み込み中…</div>`;try{const d=await unpack(q.year);if(token===renderId){const range=solutionPages[q.year+'-'+q.subject+'-'+q.number];pages($('solution-pages'),d[sol.id],range?.page||0,range?.end||d[sol.id].length)}}catch(e){if(token===renderId)$('solution-pages').textContent=e.message}}
$('start').onclick=()=>{queue=filtered();pos=0;state.queue=queue.map(q=>q.id);state.filters=Object.fromEntries(['stage','subject','year','mode'].map(id=>[id,$(id).value]));if(queue.length)render();else $('desk').innerHTML='<h2>この条件に合う問題はありません。</h2><p>科目・年度・出題範囲を変えてください。</p>'};$('resume').onclick=()=>{queue=(state.queue||[]).map(id=>questions.find(q=>q.id===id)).filter(Boolean);if(!queue.some(q=>q.id===state.last))queue=questions;for(const [id,value]of Object.entries(state.filters||{}))if($(id))$(id).value=value;pos=queue.findIndex(q=>q.id===state.last);if(pos>=0)render()};stats();
(async()=>{try{[catalog,answers,explanations,solutionPages]=await Promise.all([json('denken-assets/catalog.json'),json('denken-assets/answers.json'),json('denken-assets/explanation-links.json'),json('denken-assets/solution-pages.json')]);const glyphs=await unpack('glyphs'),defs=document.createElementNS('http://www.w3.org/2000/svg','svg');defs.setAttribute('aria-hidden','true');defs.style.cssText='position:absolute;width:0;height:0;overflow:hidden';defs.innerHTML='<defs>'+glyphs.join('')+'</defs>';document.body.prepend(defs);for(const p of catalog.filter(p=>!p.answer))p.starts.forEach((s,i)=>questions.push({...p,id:p.id+'-'+s.number,paper:p.id,number:s.number,page:s.page,end:p.starts[i+1]?.page??p.pages}));questions.sort((a,b)=>b.year-a.year||a.stage.localeCompare(b.stage)||['理論','電力','機械','法規','電力・管理','機械・制御'].indexOf(a.subject)-['理論','電力','機械','法規','電力・管理','機械・制御'].indexOf(b.subject)||a.number-b.number);
for(const [id,prop] of [['subject','subject'],['year','year']])for(const v of [...new Set(questions.map(q=>String(q[prop])))].sort((a,b)=>id==='year'?b.localeCompare(a):a.localeCompare(b))){const o=document.createElement('option');o.value=v;o.textContent=v;$(id).append(o)}$('desk').innerHTML=`<div class="empty"><span class="badge">2009–2026 · 電験二種</span><h2>紙をめくらず、一問ずつ。</h2><p>公式公開の${catalog.length}資料から、${questions.length}問を収録。</p><ol><li>問題を読み、解答・途中式を入力</li><li>一次は空欄ごとに採点。二次は公式解答で照合</li><li>間違えた問題だけを繰り返す</li></ol><p class="small">一次：2009～2026年度 ／ 二次：2009～2025年度。採点後に対応する外部解説を開けます。二次は公式の解答・計算過程も掲載。解説リンクのない問題は正答照合のみです。</p><a href="https://www.shiken.or.jp/chief/second/qa/index.html" target="_blank" rel="noopener">出典・過去問題の利用条件 ↗</a></div>`;stats()}catch(e){$('desk').textContent='教材を読み込めませんでした。再読み込みしてください。 '+e.message}})();
})();
