(()=>{'use strict';
function ready(){
 const anchor=document.querySelector('.islandTimeControls');if(!anchor)return;
 const key='ukiwa-weather-place';let place=null,request=0,last=0;
 try{place=JSON.parse(localStorage.getItem(key))}catch{}
 const style=document.createElement('style');style.textContent=`.weather-open{font:inherit;color:inherit;background:transparent;border:1px solid currentColor;border-radius:16px;padding:6px 10px;cursor:pointer;max-width:230px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.weather-dialog{width:min(460px,calc(100% - 24px));max-height:85vh;overflow:auto;border:1px solid #b9cbd4;border-radius:20px;padding:22px;background:#fffaf3;color:#253945;box-shadow:0 20px 80px #0005}.weather-dialog::backdrop{background:#10182a88}.weather-dialog button,.weather-dialog input{font:inherit;border:1px solid #a5b9c5;border-radius:10px;padding:9px;background:transparent;color:inherit}.weather-dialog button{cursor:pointer}.weather-dialog form{display:flex;gap:8px;margin:14px 0}.weather-dialog input{min-width:0;flex:1}.weather-dialog table{width:100%;border-collapse:collapse;font-size:14px}.weather-dialog th,.weather-dialog td{text-align:left;padding:9px 3px;border-bottom:1px solid #8a9ba344}.weather-dialog small{display:block;line-height:1.7;margin-top:12px}.weather-dialog a{color:inherit}.weather-results{display:grid;gap:6px}.weather-dialog h2{margin:0 0 14px;font-size:20px}html[data-theme=dark] .weather-dialog{background:#20243b;color:#eef0ff}`;document.head.append(style);
 const button=document.createElement('button');button.className='weather-open';button.textContent='☁ 天気を設定';button.setAttribute('aria-label','天気と地域の設定');anchor.after(button);
 const dialog=document.createElement('dialog');dialog.className='weather-dialog';dialog.setAttribute('aria-label','地域の天気');dialog.innerHTML='<button type="button" data-close style="float:right" aria-label="天気を閉じる">×</button><h2>島の天気便り</h2><p data-current>現在地や現場の地域を選べます。</p><div data-forecast></div><p data-status role="status"></p><button type="button" data-geo>現在地を使う</button><small>現在地は約1km単位に丸めてOpen-Meteoへ送ります。地域名の検索語も同サービスへ送信します。</small><form><input aria-label="地域名" placeholder="市区町村名（例：さいたま）" required minlength="2" maxlength="80"><button>検索</button></form><div class="weather-results"></div><p><button type="button" data-refresh>更新</button> <button type="button" data-clear>地域の保存を解除</button></p><small>選んだ地域をこの端末に保存します。現在地の追跡はしません。表示時刻は選択地域の現地時刻です。<br>天気・予報：<a href="https://open-meteo.com/" target="_blank" rel="noopener">Open-Meteo</a>（CC BY 4.0）。予報は作業可否の判断を代替しません。</small>';
 document.body.append(dialog);const $=s=>dialog.querySelector(s);const status=t=>$('[data-status]').textContent=t;
 const label=c=>c===0?'☀ 晴れ':c<=2?'🌤 晴れ時々曇り':c===3?'☁ 曇り':c<=48?'🌫 霧':c<=67?'🌧 雨':c<=77?'❄ 雪':c<=82?'🌦 にわか雨':c<=86?'❄ にわか雪':c>=95?'⛈ 雷雨':'天気不明';
 const number=(n,u)=>Number.isFinite(n)?n.toFixed(u==='℃'?0:1)+u:'—';
 async function json(url){const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();return r.json()}
 function valid(p){return p&&typeof p.name==='string'&&Number.isFinite(p.lat)&&Math.abs(p.lat)<=90&&Number.isFinite(p.lon)&&Math.abs(p.lon)<=180}
 async function update(){if(!valid(place))return;const id=++request,p={...place};status('天気を取得しています…');button.textContent='☁ '+p.name+' 読込中';$('[data-forecast]').replaceChildren();
 try{const q=new URLSearchParams({latitude:p.lat,longitude:p.lon,current:'temperature_2m,weather_code',hourly:'temperature_2m,precipitation_probability,wind_speed_10m',wind_speed_unit:'ms',timezone:'auto',forecast_days:'2'});const d=await json('https://api.open-meteo.com/v1/forecast?'+q);if(id!==request)return;if(!d.current||!d.hourly?.time)throw Error();last=Date.now();const text=p.name+' · '+label(d.current.weather_code)+' '+number(d.current.temperature_2m,'℃');button.textContent=number(d.current.temperature_2m,'℃')+' '+p.name+' '+label(d.current.weather_code);button.title=text;$('[data-current]').textContent=text;const table=document.createElement('table');table.innerHTML='<caption>これから6時間の予報</caption><thead><tr><th>時刻</th><th>気温</th><th>降水確率</th><th>風速</th></tr></thead>';const body=document.createElement('tbody');d.hourly.time.map((t,i)=>({t,i})).filter(x=>x.t>=d.current.time).slice(0,6).forEach(({t,i})=>{const tr=document.createElement('tr');[t.slice(11),number(d.hourly.temperature_2m[i],'℃'),Number.isFinite(d.hourly.precipitation_probability[i])?d.hourly.precipitation_probability[i]+'%':'—',number(d.hourly.wind_speed_10m[i],'m/s')].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});body.append(tr)});table.append(body);$('[data-forecast]').append(table);status('天気の対象時刻：'+d.current.time.replace('T',' '));}
 catch{if(id!==request)return;button.textContent='☁ 天気を取得できません';$('[data-current]').textContent=p.name;status('通信できませんでした。「更新」で再試行できます。')}}
 function choose(p){place=p;try{localStorage.setItem(key,JSON.stringify(p))}catch{}$('.weather-results').replaceChildren();update()}
 button.onclick=()=>{dialog.showModal();if(valid(place)&&Date.now()-last>1800000)update()};$('[data-close]').onclick=()=>dialog.close();$('[data-refresh]').onclick=()=>valid(place)?update():status('先に地域を選んでください。');
 $('[data-clear]').onclick=()=>{request++;place=null;try{localStorage.removeItem(key)}catch{}button.textContent='☁ 天気を設定';$('[data-current]').textContent='現在地や現場の地域を選べます。';$('[data-forecast]').replaceChildren();status('保存した地域を解除しました。')};
 $('[data-geo]').onclick=()=>{if(!navigator.geolocation){status('このブラウザーでは現在地を取得できません。地域名で検索してください。');return}const id=++request;status('位置情報の許可と取得を待っています…');navigator.geolocation.getCurrentPosition(p=>{if(id!==request)return;choose({name:'現在地付近',lat:Math.round(p.coords.latitude*100)/100,lon:Math.round(p.coords.longitude*100)/100})},error=>{if(id!==request)return;const messages={1:'位置情報の利用が許可されていません。ブラウザーと端末の位置情報設定を確認してください。アプリ内ブラウザーで許可できない場合は、Chrome・Edge・Safariなどで開くか、下の地域名検索を使ってください。',2:'この端末・ブラウザーでは現在地を取得できませんでした。端末の位置情報を有効にするか、下の地域名検索を使ってください。',3:'20秒以内に現在地を取得できませんでした。屋内やパソコンでは取得できないことがあります。再試行するか、下の地域名検索を使ってください。'};status(messages[error.code]||'現在地を取得できませんでした。下の地域名検索で天気を設定できます。');dialog.querySelector('input').focus()},{enableHighAccuracy:false,timeout:20000,maximumAge:300000})};
 let searchId=0;$('form').onsubmit=async e=>{e.preventDefault();const id=++searchId;status('地域を検索しています…');$('.weather-results').replaceChildren();try{const q=new URLSearchParams({name:$('input').value.trim(),count:'8',language:'ja',format:'json'});const d=await json('https://geocoding-api.open-meteo.com/v1/search?'+q);if(id!==searchId)return;status(d.results?.length?'地域を選んでください。':'見つかりません。市名やローマ字でも試してください。');(d.results||[]).forEach(p=>{const b=document.createElement('button');b.textContent=[p.name,p.admin1,p.country].filter(Boolean).join(' / ');b.onclick=()=>choose({name:p.name,lat:p.latitude,lon:p.longitude});$('.weather-results').append(b)})}catch{if(id===searchId)status('地域を検索できませんでした。時間をおいて再試行してください。')}};
 if(valid(place))update();else place=null;
}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
