(()=>{'use strict';
const titles=['雲海の帆船港','千年樹の集落','海の底の祈り','雲鯨の灯台','灯りを待つ水都','夕空の終着駅','茜色の円蓋都市','風車と琥珀の庭','夜光の森','星をほどく湖','月の書架','海月の天文台'];
const stories=['空を渡る船が、羽を休める港。遠い島の便りは、潮風より少し遅れて届く。','枝の上にも、根元にも、小さな暮らしがある。木陰を通る風だけが、この村の本当の年齢を知っている。','波が静まる昼にだけ、海底の聖堂が姿を見せる。誰もいない階段を、光がゆっくり降りていく。','灯台が照らすのは海ではなく、雲を泳ぐ鯨の帰り道。白い尾が消えるまで、見送っていよう。','一軒ずつ、窓に夕食の灯りがともる。その光を集めて、運河はもうひとつの街になる。','行き先のない切符を一枚。雲の切れ間に駅が現れたら、今日の旅はそこで終わり。','水面に映った街の方が、少しだけ先に夜になる。橋を渡る足音も、夕焼けに溶けていく。','風車がひと巡りするたび、庭の花がほのかに光る。ここでは日暮れを、花の数で数えている。','足元の光をたどると、森の奥に小さな泉がある。水を揺らさずに覗けば、まだ知らない星が見える。','櫂を止めると、空と湖の境目が消える。帰り道は、いちばん明るい星に預けよう。','誰かが忘れた夢は、ここで本になる。頁をめくる音だけが、静かな月のまわりを巡っている。','観測を終えた天文台に、海月の群れが訪れる。星が海へ降りる夜には、時計は少し遅く進む。'];
const themes=['昼の島','夕焼けの島','月夜の島'];let filter='all',current=0;let favorites=new Set();try{favorites=new Set(JSON.parse(localStorage.getItem('ukiwa-atlas-favorites')||'[]'))}catch{}
const $=id=>document.getElementById(id),items=titles.map((title,i)=>({i,title,story:stories[i],theme:themes[Math.floor(i/4)],src:`assets/atlas/scene-${String(i+1).padStart(2,'0')}.webp`}));
const visible=()=>items.filter(x=>filter==='all'||filter==='favorites'&&favorites.has(x.i)||String(Math.floor(x.i/4))===filter);
function render(){const list=visible();$('grid').replaceChildren(...list.map(x=>{const b=document.createElement('button');b.className='art';b.setAttribute('aria-label',x.title+'を拡大');const im=document.createElement('img');im.src=x.src;im.alt=x.title;im.loading='lazy';im.width=1536;im.height=1024;b.append(im);const meta=document.createElement('div');meta.className='meta';meta.textContent=`NO. ${String(x.i+1).padStart(2,'0')}　 /　 ${x.theme}`;const h=document.createElement('h2');h.textContent=x.title;const p=document.createElement('p');p.textContent=x.story.split('。')[0]+'。';b.append(meta,h,p);b.onclick=()=>open(x.i);return b}));$('empty').hidden=list.length>0;$('result').textContent=`${list.length} 作品`;document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)))}
function show(){const x=items[current];$('full').src=x.src;$('full').alt=x.title;$('title').textContent=x.title;$('story').textContent=x.story;$('place').textContent=`NO. ${String(current+1).padStart(2,'0')} / ${x.theme}`;$('favorite').textContent=favorites.has(current)?'♥ 保存済み':'♡ お気に入り';$('favorite').setAttribute('aria-pressed',String(favorites.has(current)));const ids=visible().map(x=>x.i);$('prev').disabled=ids.indexOf(current)<=0;$('next').disabled=ids.indexOf(current)<0||ids.indexOf(current)>=ids.length-1}
function open(i){current=i;show();$('viewer').showModal()}function step(delta){const ids=visible().map(x=>x.i),n=ids.indexOf(current)+delta;if(n>=0&&n<ids.length){current=ids[n];show()}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});$('close').onclick=()=>$('viewer').close();$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('viewer').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}if(e.key==='ArrowRight'){e.preventDefault();step(1)}});$('favorite').onclick=()=>{favorites.has(current)?favorites.delete(current):favorites.add(current);try{localStorage.setItem('ukiwa-atlas-favorites',JSON.stringify([...favorites]))}catch{$('save-note').textContent='この環境ではお気に入りを保存できません。'}show();render()};render();
})();
