(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#world'),g=canvas.getContext('2d'),portrait=$('#portrait'),pg=portrait.getContext('2d');
const creatures=[
 ['しおもち','波が運んだ、もちもちの海の精。浮き輪がお気に入り。','#c4eedf',0,'まる'],['ヒナランプ','頭の灯りで、迷った船を浜へ案内する。','#ffe5a1',0,'とり'],['ツノサンゴ','海に星が映ると、角がきらきら輝く。','#ffaeb0',0,'つの'],
 ['モモクラゲ','夕空の色を集めて、明日の雲をつくる。','#f3b6e6',1,'くらげ'],['ユウネコ','夕焼けを追いかけて、島から島へ旅をする。','#efc395',1,'ねこ'],['ホシクジラ','小さな体に、星空ひとつぶんの夢を抱えている。','#b7b9fc',1,'くじら'],
 ['ツキウサギ','月の欠片を耳にのせた、静かな島の見守り役。','#dce4ff',2,'うさぎ'],['ヨルフクロウ','夜空の地図を覚えている、ものしりな案内人。','#a0d7ea',2,'とり'],['ウキワリュウ','9つの出会いを結ぶ、島の小さな守り神。','#f2dfac',2,'つの']];
const islands=[{name:'ひだまりの浜',sky:['#78bcd0','#d2e8d1'],water:'#3c999d',sand:'#ebd5a0',grass:'#749e76',tag:'☀ GOLDEN HOUR'},{name:'琥珀の入り江',sky:['#a87baa','#f4bf9d'],water:'#886f9d',sand:'#ecc7ad',grass:'#a58c84',tag:'✦ AMBER TIDE'},{name:'月あかりの庭',sky:['#172f50','#61718f'],water:'#243f60',sand:'#9aaec0',grass:'#657b96',tag:'☾ MOON GARDEN'}];
let save={found:[],total:0,perfect:0,pearls:0,island:0,intro:false};try{const v=JSON.parse(localStorage.getItem('ukiwa-adventure-v1'));if(v&&Array.isArray(v.found)){save={...save,...v};save.found=[...new Set(v.found.filter(n=>Number.isInteger(n)&&n>=0&&n<9))];save.island=Math.max(0,Math.min(2,Number(v.island)||0))}}catch{}
let encounter=null,phase='map',start=0,attempt=0,particles=[],sound=false,ac=null,toastUntil=0;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
function persist(){try{localStorage.setItem('ukiwa-adventure-v1',JSON.stringify(save));$('#saveState').textContent='保存済み'}catch{$('#saveState').textContent='保存できません：この回の間だけ記録します'}}
function tone(win){if(!sound)return;try{ac=ac||new(window.AudioContext||window.webkitAudioContext)();ac.resume();(win?[72,76,79,84]:[60,57]).forEach((n,i)=>{const o=ac.createOscillator(),v=ac.createGain(),t=ac.currentTime+i*.09;o.frequency.value=440*2**((n-69)/12);v.gain.setValueAtTime(.035,t);v.gain.exponentialRampToValueAtTime(.0001,t+.35);o.connect(v);v.connect(ac.destination);o.start(t);o.stop(t+.36)})}catch{}}
function toast(s){$('#toast').textContent=s;toastUntil=performance.now()+3500;$('#toast').style.opacity=1}
function ellipse(c,x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill()}
function creature(c,id,x,y,size,t=0){const d=creatures[id],color=d[2],type=d[4];c.save();c.translate(x,y);c.scale(size/100,size/100);const bob=reduced?0:Math.sin(t*2)*3;c.translate(0,bob);ellipse(c,0,48,39,9,'#061c3240');
if(type==='うさぎ'){ellipse(c,-17,-47,10,30,color);ellipse(c,17,-47,10,30,color);ellipse(c,-17,-47,4,19,'#f6b9cf');ellipse(c,17,-47,4,19,'#f6b9cf')}
if(type==='ねこ'){c.fillStyle=color;c.beginPath();c.moveTo(-34,-16);c.lineTo(-32,-53);c.lineTo(-8,-28);c.lineTo(13,-29);c.lineTo(33,-53);c.lineTo(36,-12);c.fill()}
if(type==='つの'){c.strokeStyle='#ffe9a4';c.lineWidth=7;c.lineCap='round';for(const side of[-1,1]){c.beginPath();c.moveTo(side*24,-25);c.lineTo(side*32,-52);c.lineTo(side*22,-61);c.moveTo(side*30,-47);c.lineTo(side*43,-55);c.stroke()}}
if(type==='くじら'){c.fillStyle=color;c.beginPath();c.moveTo(27,12);c.quadraticCurveTo(67,26,63,-5);c.quadraticCurveTo(49,7,46,-9);c.quadraticCurveTo(37,8,27,12);c.fill()}
if(type==='くらげ'){c.strokeStyle=color;c.lineWidth=6;for(let k=-2;k<=2;k++){c.beginPath();c.moveTo(k*13,15);c.bezierCurveTo(k*13-12,45,k*13+12,40,k*13,56);c.stroke()}}
ellipse(c,0,0,type==='くじら'?44:36,type==='くらげ'?29:39,color);ellipse(c,-10,-17,13,7,'#ffffff35');if(type==='とり'){ellipse(c,-38,5,12,22,color);ellipse(c,38,5,12,22,color);c.fillStyle='#f6bb73';c.beginPath();c.moveTo(-6,9);c.lineTo(6,9);c.lineTo(0,17);c.fill()}else{c.strokeStyle='#354351';c.lineWidth=2;c.beginPath();c.arc(0,11,5,0,Math.PI);c.stroke()}
ellipse(c,-12,1,3.5,5,'#253748');ellipse(c,12,1,3.5,5,'#253748');ellipse(c,-13,-1,1.1,1.5,'white');ellipse(c,11,-1,1.1,1.5,'white');ellipse(c,-24,13,6,3,'#e6909770');ellipse(c,24,13,6,3,'#e6909770');
if(id===0||id===8){c.strokeStyle=id===8?'#fff0a7':'#fff6e2';c.lineWidth=10;c.beginPath();c.ellipse(0,32,39,13,0,0,Math.PI*2);c.stroke();c.strokeStyle='#eb947e';c.lineWidth=9;c.beginPath();c.ellipse(0,32,39,13,0,.2,.7);c.stroke()}
if(id===1){ellipse(c,0,-47,10,10,'#ffeeb2');ellipse(c,0,-47,18,18,'#ffeeb22a')}c.restore()}
function update(){const n=save.found.length;$('#count').textContent=n+' / 9';$('#caught').textContent=save.total;$('#perfect').textContent=save.perfect;$('#pearls').textContent=save.pearls;$('#progress').style.width=n/9*100+'%';$('#questTitle').textContent=n===9?'島の守り手になった！':n<3?'ひだまりの3つの出会い':n<6?'夕焼けに隠れた仲間たち':'月夜の守り神を探そう';$('#quest').textContent=n===9?'9種類の図鑑が完成。島の空に、祝福の星が流れます。':`あと${(Math.floor(n/3)+1)*3-n}種類で${n<6?'新しい島が開きます。':'図鑑が完成します。'}失敗しても、何度でも挑戦できます。`;const p=islands[save.island];$('#place').textContent='0'+(save.island+1)+' / '+p.name;$('#weather').textContent=p.tag;$('#sail').textContent=save.island===2?'最初の島へ →':'次の島へ →';$('#spots').innerHTML='';[[28,57],[52,42],[75,64]].forEach(([x,y],k)=>{const b=document.createElement('button');b.className='spot';b.style.left=x+'%';b.style.top=y+'%';b.setAttribute('aria-label',p.name+'の発見ポイント'+(k+1));b.innerHTML='✧<small>'+(['波のきらめき','草むらの気配','不思議な足あと'][k])+'</small>';b.onclick=()=>meet(k);$('#spots').append(b)});persist()}
function meet(k){const ids=[0,1,2].map(n=>save.island*3+n),unseen=ids.filter(n=>!save.found.includes(n));const id=unseen.length&&Math.random()<.78?unseen[Math.floor(Math.random()*unseen.length)]:ids[k];encounter=id;phase='catch';attempt=0;start=performance.now();$('#creatureName').textContent=creatures[id][0];$('#creatureText').textContent=creatures[id][1];$('#rarity').textContent=(id%3===2?'✦ RARE ENCOUNTER':'A LITTLE ENCOUNTER')+(save.found.includes(id)?' · 再会':' · はじめての出会い');$('#result').textContent='光の帯に重なったら、ボタンを押そう。';$('#catch').hidden=false;$('#return').hidden=true;$('#timing').hidden=false;$('#encounter').showModal()}
function position(now){return .5+.47*Math.sin((now-start)/1000*(encounter%3===2?2.1:1.65)-Math.PI/2)}
function catchIt(){if(phase!=='catch')return;const error=Math.abs(position(performance.now())-.5),width=attempt>=2?.24:.15;if(error<=width){phase='won';const fresh=!save.found.includes(encounter);if(fresh)save.found.push(encounter);save.total++;window.ukiwaTrack?.('game_capture');if(save.found.length===9&&fresh)window.ukiwaTrack?.('game_complete');save.pearls+=fresh?12:3;if(error<.045){save.perfect++;save.pearls+=5}$('#result').textContent=(error<.045?'✦ ぴったり！ ':'')+(fresh?'新しい仲間が図鑑に加わった！':'また会えたね！ 星のかけら +3');$('#catch').hidden=true;$('#return').hidden=false;$('#timing').hidden=true;tone(true);for(let i=0;i<35;i++)particles.push({x:250,y:110,vx:(Math.random()-.5)*200,vy:-Math.random()*180,life:1,color:creatures[encounter][2]});update();if(fresh&&save.found.length%3===0)toast(save.found.length===9?'✦ 図鑑完成！ あなたは島の守り手。':'新しい島への航路が開いた！')}else{attempt++;$('#result').textContent=attempt>=2?'浮き輪が大きくなった！ もう一度、光に合わせよう。':'少しずれた！ 大丈夫、もう一度。';tone(false);if(attempt>=2){$('#target').style.left='26%';$('#target').style.width='48%'}}}
function closeEncounter(){phase='map';$('#encounter').close();$('#target').style.left='35%';$('#target').style.width='30%'}
$('#catch').onclick=catchIt;$('#return').onclick=closeEncounter;$('#leave').onclick=closeEncounter;$('#encounter').addEventListener('cancel',()=>{phase='map'});document.addEventListener('keydown',e=>{if(e.code==='Space'&&phase==='catch'&&e.target.tagName!=='BUTTON'){e.preventDefault();catchIt()}});
$('#sail').onclick=()=>{const next=(save.island+1)%3;if(next>Math.floor(save.found.length/3)){toast('この島の3種類を見つけると、航路が開くよ。');return}save.island=next;window.ukiwaTrack?.(['game_island_day','game_island_sunset','game_island_moon'][next]);update();toast(islands[next].name+'に到着！')};
$('#book').onclick=()=>{$('#cards').innerHTML='';creatures.forEach((d,id)=>{const found=save.found.includes(id),e=document.createElement('div');e.className='entry'+(found?'':' unknown');if(found){const c=document.createElement('canvas');c.width=180;c.height=120;e.append(c);creature(c.getContext('2d'),id,90,61,82)}else e.innerHTML='<div class="question">?</div>';const b=document.createElement('b');b.textContent=found?d[0]:'未発見';e.append(b);const s=document.createElement('small');s.textContent=islands[d[3]].name;e.append(s);$('#cards').append(e)});$('#collection').showModal()};$('#closeBook').onclick=()=>$('#collection').close();$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='音 '+(sound?'ON':'OFF');$('#sound').setAttribute('aria-pressed',sound);if(sound)tone(true)};
$('#begin').onclick=()=>{$('#intro').close();save.intro=true;persist()};
function draw(now){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}g.setTransform(dpr,0,0,dpr,0,0);const p=islands[save.island],t=reduced?0:now/1000,sky=g.createLinearGradient(0,0,0,h);sky.addColorStop(0,p.sky[0]);sky.addColorStop(1,p.sky[1]);g.fillStyle=sky;g.fillRect(0,0,w,h);ellipse(g,w*.78,h*.23,save.island===2?24:37,save.island===2?24:37,save.island===2?'#f3eccb':'#ffe9b9');if(save.island===2){for(let i=0;i<40;i++)ellipse(g,(i*73.7)%w,25+(i*41.2)%(h*.42),1+(Math.sin(i+t)*.4),1,'#e8eacbbb')}
g.fillStyle=p.water;g.fillRect(0,h*.4,w,h*.6);g.strokeStyle='#ffffff28';g.lineWidth=1;for(let i=0;i<22;i++){let x=((i*91+t*5)%(w+100))-50,y=h*.42+(i*23)%(h*.58);g.beginPath();g.moveTo(x,y);g.quadraticCurveTo(x+14,y+4,x+35,y);g.stroke()}
// Three hand-drawn islands and their reflected shores.
[[.27,.60,.22],[.54,.46,.20],[.77,.68,.19]].forEach(([x,y,r],k)=>{ellipse(g,w*x,h*y+16,w*r,h*.07,'#143c4b22');ellipse(g,w*x,h*y,w*r,h*.09,p.sand);ellipse(g,w*x,h*y-9,w*r*.88,h*.07,p.grass);for(let i=0;i<5;i++){const tx=w*x+(i-2)*w*r*.29,ty=h*y-25-Math.sin(i*2+k)*9;g.fillStyle='#5b6466';g.fillRect(tx-2,ty-18,4,20);ellipse(g,tx,ty-20,10+3*Math.sin(i),17,p.grass==='#749e76'?'#3d7d69':save.island===1?'#856b86':'#465f7e')}ellipse(g,w*x+w*r*.4,h*y-4,7,5,'#e8d3b1')});
const bob=Math.sin(t*1.8)*3;g.save();g.translate(w*.49,h*.77+bob);g.strokeStyle='#fff0d2';g.lineWidth=8;g.beginPath();g.ellipse(0,0,20,9,0,0,Math.PI*2);g.stroke();g.strokeStyle='#e99984';g.beginPath();g.ellipse(0,0,20,9,0,.2,1);g.stroke();g.restore();
if(save.found.length===9){for(let i=0;i<6;i++){const x=(t*65+i*173)%(w+100)-50,y=60+i*22;g.strokeStyle='#fff3bba0';g.beginPath();g.moveTo(x,y);g.lineTo(x-22,y-10);g.stroke()}}
if(encounter!==null&&$('#encounter').open){pg.clearRect(0,0,500,260);const halo=pg.createRadialGradient(250,130,10,250,130,140);halo.addColorStop(0,creatures[encounter][2]+'45');halo.addColorStop(1,'#132a3200');pg.fillStyle=halo;pg.fillRect(0,0,500,260);creature(pg,encounter,250,130,145,t);if(phase==='catch')$('#needle').style.left=(position(now)*100)+'%';particles=particles.filter(p=>p.life>0);particles.forEach(p=>{p.x+=p.vx*.016;p.y+=p.vy*.016;p.vy+=3;p.life-=.015;pg.globalAlpha=Math.max(0,p.life);ellipse(pg,p.x,p.y,3,3,p.color)});pg.globalAlpha=1}
if(now>toastUntil)$('#toast').style.opacity=0;requestAnimationFrame(draw)}
$('#target').style.left='35%';$('#target').style.width='30%';update();if(!save.intro)$('#intro').showModal();requestAnimationFrame(draw);
})();
