(()=>{'use strict';
const titles=['雲海の帆船港','千年樹の集落','海の底の祈り','雲鯨の灯台','灯りを待つ水都','夕空の終着駅','茜色の円蓋都市','風車と琥珀の庭','夜光の森','星をほどく湖','月の書架','海月の天文台'];
const stories=['空を渡る船が、羽を休める港。遠い島の便りは、潮風より少し遅れて届く。','枝の上にも、根元にも、小さな暮らしがある。木陰を通る風だけが、この村の本当の年齢を知っている。','波が静まる昼にだけ、海底の聖堂が姿を見せる。誰もいない階段を、光がゆっくり降りていく。','灯台が照らすのは海ではなく、雲を泳ぐ鯨の帰り道。白い尾が消えるまで、見送っていよう。','一軒ずつ、窓に夕食の灯りがともる。その光を集めて、運河はもうひとつの街になる。','行き先のない切符を一枚。雲の切れ間に駅が現れたら、今日の旅はそこで終わり。','水面に映った街の方が、少しだけ先に夜になる。橋を渡る足音も、夕焼けに溶けていく。','風車がひと巡りするたび、庭の花がほのかに光る。ここでは日暮れを、花の数で数えている。','足元の光をたどると、森の奥に小さな泉がある。水を揺らさずに覗けば、まだ知らない星が見える。','櫂を止めると、空と湖の境目が消える。帰り道は、いちばん明るい星に預けよう。','誰かが忘れた夢は、ここで本になる。頁をめくる音だけが、静かな月のまわりを巡っている。','観測を終えた天文台に、海月の群れが訪れる。星が海へ降りる夜には、時計は少し遅く進む。'];
titles.push('天空の観測庭','真珠の眠る都','雪晶の灯り');stories.push('雲より高い庭では、もう使われない観測器が朝日を待っている。海へ落ちる滝の音を聴いていると、昨日までの悩みが少しだけ小さくなる。桟橋の浮き輪は、空を旅した誰かの忘れ物。','日が沈む少し前、海底の真珠が一斉に目を覚ます。貝殻の屋根をすべる光を追って、魚たちは家路につく。波の上と下で、ふたつの夕暮れが静かに重なっている。','雪をかぶった結晶の木は、風が吹くと小さな鈴の音を立てる。湖の向こうには、まだ灯りの消えない一軒の家。オーロラが薄れるまで、温かい飲み物を片手に窓辺で待っていよう。');titles.push('氷晶の入り江','星砂の漂流島','潮待ちの書庫');stories.push('氷の門をくぐると、入り江だけは春のように静かだった。桟橋につながれた小舟は、次の雪解けを待っている。浮き輪に残った潮の香りだけが、この海の温かさを覚えていた。','夕焼けが砂に触れると、埋もれた星が一つずつ光り始める。帆を張った小舟は、波のない砂丘をゆっくり渡っていく。古い観測器が指すのは北ではなく、旅人の帰りたい場所。','月が満ちるまで、書庫へ続く石段は海の下に眠っている。今夜は潮が引き、読みかけの物語へ戻る道が現れた。空を泳ぐ海月が、閉じ忘れたページをそっと照らす。');titles.push(...["旅する亀の庭", "風奏の谷", "星実の果樹園"]);stories.push(...["島が動いた、と誰かが言った。朝食の湯気が消えるころ、大きな亀は次の入り江へ歩き始める。庭の住人たちは今日も花に水をやり、知らない海岸へ届く昼を待っている。", "海から来た風が、谷の大きな管を通って低く歌う。橋を渡るたびに違う音が重なり、帰り道はいつのまにか一曲になる。最後の鐘が鳴ったら、夕食の支度を始めよう。", "この島では星を摘まず、熟すまで待つ。透きとおった果実の中で、小さな星座がゆっくり向きを変える。庭師が窓の灯りを消すと、今夜生まれた光だけが小道を照らした。"]);const themeIndex=i=>i<12?Math.floor(i/4):(i-12)%3;
const themes=['昼の島','夕焼けの島','月夜の島'];let filter='all',current=0;let favorites=new Set();try{favorites=new Set(JSON.parse(localStorage.getItem('ukiwa-atlas-favorites')||'[]'))}catch{}
const $=id=>document.getElementById(id),items=titles.map((title,i)=>({i,title,story:stories[i],theme:themes[themeIndex(i)],src:`assets/atlas/scene-${String(i+1).padStart(2,'0')}.webp`}));
const visible=()=>items.filter(x=>filter==='all'||filter==='favorites'&&favorites.has(x.i)||filter==='new'&&x.i>=18||String(themeIndex(x.i))===filter);
function render(){const list=visible();$('grid').replaceChildren(...list.map(x=>{const b=document.createElement('button');b.className='art';b.setAttribute('aria-label',x.title+'を拡大');const im=document.createElement('img');im.src=x.src;im.alt=x.title;im.loading='lazy';im.width=1536;im.height=1024;b.append(im);const meta=document.createElement('div');meta.className='meta';meta.textContent=`NO. ${String(x.i+1).padStart(2,'0')}　 /　 ${x.theme}`;const h=document.createElement('h2');h.textContent=x.title;const p=document.createElement('p');p.textContent=x.story.split('。')[0]+'。';b.append(meta,h,p);b.onclick=()=>open(x.i);return b}));$('empty').hidden=list.length>0;$('random').disabled=list.length===0;$('result').textContent=`${list.length} 作品`;document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)))}
let taleCurrent=-1;
function renderTale(){
 if(taleCurrent===current)return;taleCurrent=current;
 const tale=window.UkiwaAtlasTales?.[String(current+1)];
 $('tale').open=false;$('tale').hidden=!tale;$('to-tale').hidden=!tale;
 $('viewer').scrollTop=0;
 if(!tale)return;
 $('tale-summary').textContent=`この島の物語を読む · 約${tale.minutes}分`;
 $('tale-title').textContent=tale.title;
 $('tale-meta').textContent=`${tale.genre} ／ 読む目安 約${tale.minutes}分`;
 $('tale-body').replaceChildren(...tale.paragraphs.map(text=>{const p=document.createElement('p');p.textContent=text;return p}));
}
function show(){const x=items[current];renderTale();$('full').src=x.src;$('full').alt=x.title;$('title').textContent=x.title;$('story').textContent=x.story;$('place').textContent=`NO. ${String(current+1).padStart(2,'0')} / ${x.theme}`;$('favorite').textContent=favorites.has(current)?'♥ 保存済み':'♡ お気に入り';$('favorite').setAttribute('aria-pressed',String(favorites.has(current)));const ids=visible().map(x=>x.i);$('prev').disabled=ids.indexOf(current)<=0;$('next').disabled=ids.indexOf(current)<0||ids.indexOf(current)>=ids.length-1}
function open(i){taleCurrent=-1;current=i;show();$('viewer').showModal()}function step(delta){const ids=visible().map(x=>x.i),n=ids.indexOf(current)+delta;if(n>=0&&n<ids.length){current=ids[n];show()}}
const artBack=()=>{$('viewer').scrollTo({top:0,behavior:'instant'});$('to-tale').focus({preventScroll:true})};
$('back-to-art').onclick=artBack;$('tale-back').onclick=artBack;
$('to-tale').onclick=()=>{$('tale').open=true;$('tale').scrollIntoView({block:'start',behavior:'instant'});$('tale-summary').focus({preventScroll:true})};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});$('random').onclick=()=>{const list=visible();if(list.length)open(list[Math.floor(Math.random()*list.length)].i)};$('close').onclick=()=>$('viewer').close();$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('viewer').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}if(e.key==='ArrowRight'){e.preventDefault();step(1)}});$('favorite').onclick=()=>{favorites.has(current)?favorites.delete(current):favorites.add(current);try{localStorage.setItem('ukiwa-atlas-favorites',JSON.stringify([...favorites]))}catch{$('save-note').textContent='この環境ではお気に入りを保存できません。'}show();render()};render();
})();
