(()=>{
const read=k=>{try{return localStorage.getItem(k)}catch{return null}},save=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const themeAt=h=>h>=6&&h<16?'light':h>=16&&h<19?'sunset':'dark';
let automatic=read('ukiwa-theme-mode')!=='manual';
function apply(){const now=new Date();let theme=automatic?themeAt(now.getHours()):read('ukiwa-theme');if(!['light','sunset','dark'].includes(theme))theme='light';const changed=document.documentElement.dataset.theme!==theme;document.documentElement.dataset.theme=theme;save('ukiwa-theme',theme);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#031326':theme==='sunset'?'#fff1df':'#eef8ff');const picker=document.getElementById('sceneSelect');if(picker)picker.value=theme;const clock=document.getElementById('islandClock');if(clock){clock.textContent=now.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',hour12:false});clock.dateTime=now.toISOString();clock.title='端末の現地時刻';}const box=document.getElementById('islandAuto');if(box)box.checked=automatic;if(changed)dispatchEvent(new Event('ukiwa-theme-change'));}
apply();function ready(){const picker=document.getElementById('sceneSelect');if(picker){const controls=document.createElement('span');controls.className='islandTimeControls';controls.style.cssText='display:inline-flex;align-items:center;gap:7px;font-size:12px;white-space:nowrap';controls.innerHTML='<time id="islandClock" aria-label="端末の現在時刻" style="font-variant-numeric:tabular-nums"></time><label title="6～16時：昼／16～19時：夕焼け／19～6時：月夜"><input id="islandAuto" type="checkbox">自動</label>';picker.closest('label').after(controls);document.getElementById('islandAuto').addEventListener('change',e=>{automatic=e.target.checked;save('ukiwa-theme-mode',automatic?'auto':'manual');apply()});picker.addEventListener('change',()=>{automatic=false;save('ukiwa-theme-mode','manual');save('ukiwa-theme',picker.value);apply()});}apply();setInterval(apply,30000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();addEventListener('pageshow',apply);document.addEventListener('visibilitychange',()=>{if(!document.hidden)apply()});addEventListener('storage',e=>{if(['ukiwa-theme','ukiwa-theme-mode'].includes(e.key)){automatic=read('ukiwa-theme-mode')!=='manual';apply()}});
})();
(()=>{const s=document.createElement('script');s.src='ukiwa-analytics.js?v=footer-2';s.defer=true;document.head.append(s)})();
