(() => {
'use strict';
const lessons=[
{title:'まず、電気の通り道',short:'つながると点灯',goal:'スイッチを閉じると、なぜランプが点くのかを確かめます。',copy:'<p>電源の＋から、スイッチ、ランプを通り、0Vへ戻る道がつながると電流が流れます。</p><p><b>「開」は道が切れる。「閉」は道がつながる。</b>まずこの二つだけ覚えよう。</p>',task:'スイッチを閉じる → 開く。図の線とランプがどう変わるか見よう。',terms:'0Vはこの直流電源の戻り側。必ず大地と同じという意味ではありません。ランプは電気を使う負荷です。',q:'スイッチが開いているとき、ランプは？',a:['消える','点く'],correct:0,why:'途中で道が切れており、この回路では電流が流れないからです。'},
{title:'コイルが接点を動かす',short:'リレーの中身',goal:'操作する回路と、ランプを動かす回路を分けて見ます。',copy:'<p>リレーには、電磁石になる<b>コイル</b>と、動かされる<b>接点</b>があります。コイルに電流が流れて動作することを「励磁」と呼びます。</p><p>K1コイルが動くと、K1-a接点が閉じます。<b>同じK1という名前が、対応する組の印</b>です。</p>',task:'操作スイッチを閉じよう。上のコイルが動き、下の接点が閉じてランプが点く順番を追おう。',terms:'コイルと接点は、内部で機械的に連動します。図の上下の枝の間に電流が飛び移るわけではありません。K1は教材内の識別名です。',q:'K1-aを動かすのは？',a:['ランプ','K1コイル'],correct:1,why:'K1コイルとK1-aは同じリレーに属します。コイルの動作が接点を切り替えます。'},
{title:'a接点とb接点は、逆の動き',short:'aとbの違い',goal:'コイルが動く前と後を、二つのランプで比べます。',copy:'<p><b>a接点：</b>コイルが無励磁なら開、励磁すると閉。<br><b>b接点：</b>コイルが無励磁なら閉、励磁すると開。</p><p>「常開」「常閉」の「常」は、ここでは<b>コイルに電流を流していない基準状態</b>です。いつでも開・閉のままという意味ではありません。</p>',task:'コイルをON/OFFし、a側とb側のランプが入れ替わることを確かめよう。',terms:'NO（normally open）はa接点、NC（normally closed）はb接点。ここでは非保持形リレーを扱い、押ボタンなら「手を離した状態」を基準にします。',q:'コイルがOFFのとき、b接点は？',a:['開いている','閉じている'],correct:1,why:'b接点は基準状態で閉じています。コイルの励磁によって開きます。'},
{title:'直列は「両方」、並列は「どちらか」',short:'条件の組み合わせ',goal:'同じ二つのスイッチでも、つなぎ方で条件が変わります。',copy:'<p><b>直列：</b>AとBを続けて通るので、両方が閉じる必要があります。</p><p><b>並列：</b>Aの道とBの道に分かれるので、どちらか一方が閉じれば流れます。次の自己保持で、この「別の道」を使います。</p>',task:'Aだけ閉じたまま、直列と並列を切り替えてみよう。',terms:'直列はAND条件、並列はOR条件とも呼びます。ここでは二つともa接点のスイッチです。',q:'並列で、Aが開・Bが閉なら？',a:['ランプは点く','ランプは消える'],correct:0,why:'Bの枝に、電源から戻り側までつながる道が残っています。'},
{title:'離しても動く、自己保持',short:'STARTとSTOP',goal:'STARTと並列にあるK1-aが、動き続ける理由です。',copy:'<p>①STARTを押すとK1が励磁。<br>②連動してK1-aが閉じる。<br>③STARTを離しても、K1-aの道から電流が流れ続けます。</p><p>STOPは分岐より手前のb接点。押すと<b>両方の道をまとめて切る</b>ので、自己保持も解除します。</p>',task:'STARTを押す → 離す → STOPを押す → 離す。STOPを離しただけでは再起動しないことも見よう。',terms:'押す・離すボタンは手の動きを一つずつ再現します。自己保持は電源がある間の回路動作で、コイルに電気を保存する機能ではありません。',q:'停止後、STARTを離したままSTOPだけ戻すと？',a:['自動で再起動する','停止したまま'],correct:1,why:'STARTもK1-aも開いています。コイルへつながる道がないためです。'},
{title:'相手が動いていたら、入れない',short:'インターロック',goal:'相手のb接点が、自分のコイルへの道を切ります。',copy:'<p>K1の回路に<b>K2-b</b>、K2の回路に<b>K1-b</b>を入れます。K1が動くとK1-bが開くため、K2の操作をしてもK2へ電流が流れません。</p><p>この例は、操作を保持する間だけ動く回路です。自己保持は含めていません。</p>',task:'K1操作をON → K2操作もON。K2が動かない理由を図で探そう。次にK1操作をOFFにすると、残っていたK2操作で何が起きる？',terms:'一方が動作中の定常状態を学ぶモデルです。実機の同時操作時の競合・接点溶着・機械的インターロックは再現しません。これだけで安全回路になるわけではありません。',q:'K1が励磁しているとき、K2を阻止する接点は？',a:['K1-b','K2-b'],correct:0,why:'K2の回路に入れたK1-bが開き、K2コイルへの通り道を切ります。'}
];
const $=id=>document.getElementById(id);let step=0,s;
const initial=()=>({power:true,a:false,b:false,parallel:false,start:false,stop:false,k:false,k2:false});
function settle(){if(!s.power){s.k=s.k2=false;return;}if(step===4)s.k=!s.stop&&(s.start||s.k);else if(step===5){const k=s.k&&s.a,k2=s.k2&&s.b;s.k=s.a&&!k2;s.k2=s.b&&!s.k;}else s.k=s.a;}
function action(key){if(key==='reset'){s=initial();}else s[key]=!s[key];settle();draw();}
const text=(x,y,t)=>`<text x="${x}" y="${y}" text-anchor="middle">${t}</text>`;
const wire=(d,on)=>`<path class="wire ${on?'hot':''}" d="${d}"/>`;
function contact(x,y,label,closed,on){return wire(`M${x-42} ${y}H${x-16}M${x+16} ${y}H${x+42}`,on)+`<circle cx="${x-16}" cy="${y}" r="3" fill="#244c62"/><circle cx="${x+16}" cy="${y}" r="3" fill="#244c62"/>`+wire(`M${x-16} ${y}L${x+16} ${closed?y:y-18}`,on&&closed)+text(x,y-33,label)+text(x,y+28,closed?'閉':'開');}
const load=(x,y,label,on)=>`<rect class="symbol ${on?'active':''}" x="${x-34}" y="${y-23}" width="68" height="46" rx="22"/>${text(x,y+6,label)}${text(x,y+47,on?'ON':'OFF')}`;
function row(y,items,label,on){let out=wire(`M30 ${y}H480`,on);for(const [x,n,c]of items)out+=`<rect x="${x-43}" y="${y-24}" width="86" height="50" fill="#f5f9fc"/>`+contact(x,y,n,c,on);return out+load(415,y,label,on);}
function draw(){const power=s.power;let h=240,parts='',state='';if(step===0){let on=power&&s.a;parts=row(110,[[190,'スイッチ',s.a]],'ランプ',on);state=on?'スイッチが閉。＋ → スイッチ → ランプ → 0Vの道がつながり、点灯。':'スイッチが開、または電源OFF。電流が流れず消灯。';}
if(step===1||step===2){h=step===2?420:310;parts=row(100,[[190,'操作SW',s.a]],'K1',s.k&&power)+row(230,[[190,'K1-a',s.k]],'ランプa',s.k&&power);if(step===2)parts+=row(350,[[190,'K1-b',!s.k]],'ランプb',!s.k&&power);state=s.k?'K1が励磁 → K1-aが閉。'+(step===2?'K1-bは開き、b側は消灯。':'接点側の回路もつながり、ランプが点灯。'):'K1は無励磁 → K1-aは開。'+(step===2?'K1-bは閉。電源ONならb側が点灯。':'ランプへの道は切れています。');}
if(step===3){h=310;let on=power&&(s.parallel?(s.a||s.b):(s.a&&s.b));if(!s.parallel)parts=row(140,[[120,'A',s.a],[265,'B',s.b]],'ランプ',on);else parts=wire('M30 150H80M300 150H480',on)+wire('M80 100V220M300 100V220',false)+wire('M80 150V100M300 100V150',power&&s.a)+wire('M80 150V220M300 220V150',power&&s.b)+wire('M80 100H300',power&&s.a)+wire('M80 220H300',power&&s.b)+`<rect x="147" y="75" width="86" height="55" fill="#f5f9fc"/><rect x="147" y="195" width="86" height="55" fill="#f5f9fc"/>`+contact(190,100,'A',s.a,power&&s.a)+contact(190,220,'B',s.b,power&&s.b)+load(415,150,'ランプ',on);state=(s.parallel?'並列：AかBのどちらか':'直列：AとBの両方')+'が閉じると点灯。今は'+(on?'点灯しています。':'消灯しています。');}
if(step===4){h=320;parts=wire('M30 150H180M340 150H480',s.k)+wire('M180 100V230M340 100V230',false)+wire('M180 150V100M340 100V150',s.k&&s.start)+wire('M180 150V230M340 230V150',s.k)+`<rect x="47" y="125" width="86" height="55" fill="#f5f9fc"/>`+contact(90,150,'STOP b',!s.stop,s.k)+wire('M180 100H340',s.k&&s.start)+wire('M180 230H340',s.k)+`<rect x="217" y="75" width="86" height="55" fill="#f5f9fc"/><rect x="217" y="205" width="86" height="55" fill="#f5f9fc"/>`+contact(260,100,'START a',s.start,s.k&&s.start)+contact(260,230,'K1-a',s.k,s.k)+load(415,150,'K1',s.k);state=!power?'電源OFF。K1が無励磁になり、自己保持接点も開きます。':s.stop?'STOPを押したのでb接点が開。K1はOFF、K1-aも開いて保持解除。':s.k?(s.start?'STARTが閉じてK1がON。K1-aも閉じ、並列の保持経路ができました。':'STARTは開。でも下のK1-aを通る道があるため、K1はONのまま。'):'K1はOFF。STARTとK1-aが開いているので、STOPが閉じていても起動しません。';}
if(step===5){h=320;parts=row(100,[[110,'操作1',s.a],[260,'K2-b',!s.k2]],'K1',s.k)+row(235,[[110,'操作2',s.b],[260,'K1-b',!s.k]],'K2',s.k2);state=s.k?'K1がON → 下段のK1-bが開。操作2をONにしてもK2は動きません。':s.k2?'K2がON → 上段のK2-bが開。操作1をONにしてもK1は動きません。':'両方OFF。相手のb接点は、どちらも閉じています。';}
$('diagram').innerHTML=`<svg viewBox="0 0 510 ${h}" role="img" aria-label="${lessons[step].title}の現在の回路。${state}">${wire(`M30 50V${h-25}M480 50V${h-25}`,false)}${text(30,28,power?'＋':'OFF')}${text(480,28,'0V')}${parts}</svg>`;
$('state').textContent=state;const controls=[];function btn(key,label,value){controls.push(`<button data-action="${key}" aria-pressed="${value}">${label}</button>`);}
if(step<=2)btn('a',s.a?'操作スイッチを開く':'操作スイッチを閉じる',s.a);if(step===3){btn('a','A：'+(s.a?'閉 → 開く':'開 → 閉じる'),s.a);btn('b','B：'+(s.b?'閉 → 開く':'開 → 閉じる'),s.b);btn('parallel',s.parallel?'並列 → 直列にする':'直列 → 並列にする',s.parallel);}
if(step===4){btn('start',s.start?'STARTを離す':'STARTを押す',s.start);btn('stop',s.stop?'STOPを離す':'STOPを押す',s.stop);btn('power',s.power?'制御電源をOFF':'制御電源をON',s.power);}
if(step===5){btn('a','操作1：'+(s.a?'ON → OFF':'OFF → ON'),s.a);btn('b','操作2：'+(s.b?'ON → OFF':'OFF → ON'),s.b);}
$('controls').innerHTML=controls.join('');}
function lesson(n){step=n;s=initial();const l=lessons[n];$('number').textContent=`STEP ${n+1} / 6`;$('title').textContent=l.title;$('goal').textContent=l.goal;$('copy').innerHTML=l.copy;$('task').textContent=l.task;$('terms').textContent=l.terms;$('question').textContent=l.q;$('answers').innerHTML=l.a.map((a,i)=>`<button data-answer="${i}">${a}</button>`).join('');$('feedback').textContent='';$('progress').textContent=`${n+1} / 6`;$('prev').disabled=n===0;$('next').disabled=n===5;$('steps').innerHTML=lessons.map((l,i)=>`<button data-step="${i}" ${i===n?'aria-current="step"':''}><small>STEP ${i+1}</small>${l.short}</button>`).join('');settle();draw();}
$('steps').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b)lesson(+b.dataset.step);});$('controls').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b){const key=b.dataset.action;action(key);$('controls').querySelector(`[data-action="${key}"]`)?.focus();}});$('reset').onclick=()=>action('reset');$('prev').onclick=()=>lesson(Math.max(0,step-1));$('next').onclick=()=>lesson(Math.min(5,step+1));$('answers').addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(!b)return;const l=lessons[step];$('feedback').textContent=(+b.dataset.answer===l.correct?'正解。':'もう一度、図で確かめよう。')+l.why;});lesson(0);
})();