import {test} from 'node:test';import assert from 'node:assert/strict';
import {CARDS,CARD_IDS} from '../dist/cards.js';
import {newGame,seeded,apply,settle,legalActions,targets,attackTargets} from '../dist/engine.js';
import {chooseAction,publicView} from '../dist/ai.js';
function fixture(){const s=newGame(seeded(1));s.active=0;s.turn=3;s.first=0;s.winner=null;s.logs=[];s.events=[];for(const p of s.players){p.life=20;p.energy=8;p.maxEnergy=8;p.hand=[];p.board=[];p.deck=[];p.turns=1;p.fatigue=0}return s}
const card=(id,uid=id)=>({uid,card:id});
const unit=(id,uid=id,extra={})=>({...card(id,uid),attack:CARDS[id].attack,health:CARDS[id].health,maxHealth:CARDS[id].health,ready:true,born:1,...extra});
const play=(s,id,target)=>apply(s,0,{type:'play',uid:id,...(target?{target}:{})});
test('10 frozen definitions, two of each, 20 cards each, unique IDs and initial draw',()=>{const s=newGame(seeded(42));assert.equal(CARD_IDS.length,10);const all=[];s.players.forEach((p,i)=>{assert.equal(p.hand.length,3);assert.equal(p.deck.length,17);assert.equal(p.maxEnergy,i===s.first?1:0);for(const id of CARD_IDS)assert.equal([...p.deck,...p.hand].filter(c=>c.card===id).length,2);all.push(...p.deck,...p.hand)});assert.equal(new Set(all.map(c=>c.uid)).size,40);assert(Object.isFrozen(CARDS.spark))});
test('first turn skips draw; second player gets draw and 1 energy; refresh caps at 8',()=>{let s=newGame(seeded(2));const second=1-s.first;s=apply(s,s.active,{type:'end'}).state;assert.equal(s.active,second);assert.equal(s.players[second].hand.length,4);assert.equal(s.players[second].energy,1);s.players[1-second].maxEnergy=8;s.players[1-second].energy=2;s=apply(s,second,{type:'end'}).state;assert.equal(s.players[1-second].energy,8)});
test('failed commands do not mutate state or consume cards/energy',()=>{const s=fixture();s.players[0].hand=[card('tesla')];s.players[0].energy=6;const before=JSON.stringify(s),r=play(s,'tesla');assert(!r.ok);assert.equal(JSON.stringify(s),before);assert.equal(r.state,s);assert(!apply(s,1,{type:'end'}).ok)});
test('summoning sickness, rush and double attack enforcement',()=>{let s=fixture();s.players[0].hand=[card('diode'),card('spark')];s=play(s,'diode').state;assert(!apply(s,0,{type:'attack',uid:'diode',target:{side:1,uid:'hero'}}).ok);s=play(s,'spark').state;let r=apply(s,0,{type:'attack',uid:'spark',target:{side:1,uid:'hero'}});assert(r.ok);assert.equal(r.state.players[1].life,19);assert(!apply(r.state,0,{type:'attack',uid:'spark',target:{side:1,uid:'hero'}}).ok)});
test('same-name instances independent and cannot replay consumed instance',()=>{let s=fixture();s.players[0].hand=[card('spark','a'),card('spark','b')];s=play(s,'a').state;assert(!play(s,'a').ok);s=play(s,'b').state;s.players[0].board[0].health=0;settle(s);assert.equal(s.players[0].board[0].uid,'b');assert.equal(CARDS.spark.health,1)});
test('board capacity 5 prevents summons',()=>{const s=fixture();s.players[0].board=Array.from({length:5},(_,i)=>unit('spark','u'+i));s.players[0].hand=[card('spark')];assert(!play(s,'spark').ok);assert.equal(s.players[0].energy,8)});
test('guard blocks normal attacks, not targeted spells; target ownership validated',()=>{let s=fixture();s.players[0].board=[unit('diode')];s.players[1].board=[unit('resistor'),unit('transistor')];s.players[0].hand=[card('lightning')];assert.deepEqual(attackTargets(s,0),[{side:1,uid:'resistor'}]);assert(!apply(s,0,{type:'attack',uid:'diode',target:{side:1,uid:'hero'}}).ok);assert(!play(s,'lightning',{side:0,uid:'diode'}).ok);s=play(s,'lightning',{side:1,uid:'hero'}).state;assert.equal(s.players[1].life,16)});
test('combat simultaneous, including exhausted retaliation; face has no retaliation',()=>{let s=fixture();s.players[0].board=[unit('diode')];s.players[1].board=[unit('diode','enemy',{ready:false})];s=apply(s,0,{type:'attack',uid:'diode',target:{side:1,uid:'enemy'}}).state;assert.equal(s.players[0].board.length,0);assert.equal(s.players[1].board.length,0);assert.equal(s.events.filter(e=>e.kind==='destroy').length,2);s=fixture();s.players[0].board=[unit('diode')];s=apply(s,0,{type:'attack',uid:'diode',target:{side:1,uid:'hero'}}).state;assert.equal(s.players[0].board[0].health,3);assert.equal(s.players[1].life,17)});
test('combat damage persists between turns, attack readiness refreshes',()=>{let s=fixture();s.players[0].board=[unit('coil')];s.players[1].board=[unit('spark')];s=apply(s,0,{type:'attack',uid:'coil',target:{side:1,uid:'spark'}}).state;assert.equal(s.players[0].board[0].health,3);assert(!s.players[0].board[0].ready);s=apply(s,0,{type:'end'}).state;s=apply(s,1,{type:'end'}).state;assert.equal(s.players[0].board[0].health,3);assert(s.players[0].board[0].ready)});
test('capacitor heals capped at 20; battlecry happens only once',()=>{let s=fixture();s.players[0].life=19;s.players[0].hand=[card('capacitor')];s=play(s,'capacitor').state;assert.equal(s.players[0].life,20);assert(!play(s,'capacitor').ok);assert.equal(s.events.filter(e=>e.kind==='heal').length,1)});
test('coil draws; hand overflow burns and logs; fatigue increases independently',()=>{let s=fixture();s.players[0].hand=[card('coil')];s.players[0].deck=[card('spark')];s=play(s,'coil').state;assert.equal(s.players[0].hand[0].card,'spark');s=fixture();s.players[1].hand=Array.from({length:8},(_,i)=>card('spark','h'+i));s.players[1].deck=[card('diode')];s=apply(s,0,{type:'end'}).state;assert.equal(s.players[1].hand.length,8);assert.equal(s.players[1].deck.length,0);assert(s.logs.some(l=>l.includes('破棄')));s=fixture();for(let i=0;i<4;i++)s=apply(s,s.active,{type:'end'}).state;assert.equal(s.players[0].life,17);assert.equal(s.players[1].life,17);assert.equal(s.players[0].fatigue,2)});
test('coil fatigue can end game immediately',()=>{const s=fixture();s.players[0].life=1;s.players[0].hand=[card('coil')];const r=play(s,'coil');assert.equal(r.state.winner,1);assert(!apply(r.state,0,{type:'end'}).ok)});
test('tesla area damage simultaneous and only on enemy board',()=>{let s=fixture();s.players[0].hand=[card('tesla')];s.players[0].board=[unit('spark','friendly')];s.players[1].board=[unit('spark','a'),unit('capacitor','b'),unit('resistor','c')];s=play(s,'tesla').state;assert.equal(s.players[0].board.length,2);assert.deepEqual(s.players[1].board.map(u=>[u.uid,u.health]),[['c',2]]);assert.equal(s.events.filter(e=>e.kind==='damage').length,1)});
test('short requires enemy unit and deals 3; no consumption without valid target',()=>{const s=fixture();s.players[0].hand=[card('short')];assert.equal(targets(s,0,'short').length,0);assert(!play(s,'short').ok);s.players[1].board=[unit('diode')];assert(!play(s,'short',{side:1,uid:'hero'}).ok);assert(!play(s,'short').ok);assert.equal(s.players[0].energy,8);assert.equal(play(s,'short',{side:1,uid:'diode'}).state.players[1].board.length,0)});
test('overclock permanent attack +2, not health or readiness; cannot buff enemy',()=>{let s=fixture();s.players[0].hand=[card('overclock')];s.players[0].board=[unit('diode','u',{ready:false,health:2})];assert(!play(s,'overclock',{side:1,uid:'u'}).ok);s=play(s,'overclock',{side:0,uid:'u'}).state;assert.deepEqual([s.players[0].board[0].attack,s.players[0].board[0].health,s.players[0].board[0].ready],[5,2,false]);assert.equal(CARDS.diode.attack,3)});
test('life zero wins; simultaneous deaths draw; no postgame action',()=>{let s=fixture();s.players[1].life=4;s.players[0].hand=[card('lightning')];s=play(s,'lightning',{side:1,uid:'hero'}).state;assert.equal(s.winner,0);assert(!apply(s,0,{type:'end'}).ok);s=fixture();s.players[0].life=0;s.players[1].life=-1;settle(s);assert.equal(s.winner,'draw');assert.equal(legalActions(s).length,0)});
test('AI finds buff + attack lethal through a guard with spell removal',()=>{let s=fixture();s.active=1;s.players[0].life=5;s.players[0].board=[unit('resistor','guard',{health:3})];s.players[1].hand=[card('short','removal'),card('overclock','buff')];s.players[1].board=[unit('diode','attacker')];for(let i=0;i<5&&s.winner===null;i++){const a=chooseAction(s);assert.notEqual(a.type,'end');const r=apply(s,1,a);assert(r.ok);s=r.state}assert.equal(s.winner,1)});
test('AI does not consult opposing hand or deck order, including own hidden deck',()=>{const s=fixture();s.active=1;s.players[1].hand=[card('spark')];s.players[0].hand=[card('tesla')];s.players[0].deck=[card('short')];s.players[1].deck=[card('diode')];const t=structuredClone(s);t.players[0].hand=[card('spark','secret')];t.players[0].deck=[card('tesla','secret2')];t.players[1].deck=[card('lightning','secret3')];assert.deepEqual(publicView(s,1),publicView(t,1));assert.deepEqual(chooseAction(s),chooseAction(t))});
test('CPU chooses favorable trade before face when enemy threat is high',()=>{const s=fixture();s.active=1;s.players[1].board=[unit('diode','mine',{health:4})];s.players[0].board=[unit('diode','foe',{health:2})];const a=chooseAction(s);assert.equal(a.type,'attack');assert.equal(a.target.uid,'foe')});
test('seeded full CPU-vs-CPU games finish legally with bounded actions',()=>{for(let seed=10;seed<14;seed++){let s=newGame(seeded(seed)),moves=0;while(s.winner===null&&moves<600){const a=chooseAction(s,s.active);const r=apply(s,s.active,a);assert(r.ok);s=r.state;moves++;for(const p of s.players){assert(p.hand.length<=8);assert(p.board.length<=5);assert(p.energy>=0&&p.energy<=8);assert(p.life<=20);assert(p.board.every(u=>u.health>0));}}assert.notEqual(s.winner,null);assert(moves<600);console.log(`seed ${seed}: ${s.turn} turns / ${moves} actions / winner ${s.winner}`)}});
import {DECKS} from '../dist/decks.js';
test('every tactical deck has 20 valid unique instances and all matchups finish',()=>{
 for(const [name,a]of Object.entries(DECKS))for(const [other,b]of Object.entries(DECKS)){
  assert.equal(a.cards.length,20);assert.ok(a.cards.every(id=>CARDS[id]));
  let s=newGame(seeded(32),[a.cards,b.cards]);
  assert.equal(new Set(s.players.flatMap(p=>[...p.deck,...p.hand]).map(c=>c.uid)).size,40);
  for(let n=0;n<350&&s.winner===null;n++){let r=apply(s,s.active,chooseAction(s));assert.ok(r.ok,name+'/'+other);s=r.state}
  assert.notEqual(s.winner,null,name+'/'+other);
 }
});
